profile: "v7.4_2017"   # *

run:
  project_dir: "/sciclone/schism10/feiye/STOFS3D-v7.4/"
  runid: "R01"  # *
  hgrid_path: "/sciclone/schism10/Hgrid_projects/STOFS3D-v7.4/I01/hgrid.gr3"

model:
  version: "v7p4"
  rnday: 396
  startdate: "2016-12-01"  # *
  replace_nwm_with_usgs: True


runtime:
  # optional scratch target for outputs symlink:
  scr_dir: "/sciclone/scr10/feiye/STOFS3D-v7.4/"

inputs:
  bctides: true
  vgrid: false
  gr3: false
  nudge_gr3: false
  shapiro: false
  drag: false
  elev_ic: false
  flux_th: true
  source_sink: true
  soil: false
  "hotstart.nc": true
  "3D.th.nc": true
  "*nu.nc": true
  "elev2D.th.nc": true
  "*.prop": false
